name: Build RisingOS

on:
  push:   
    branches:
      - '*'  
  pull_request:  
    branches:
      - '*'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # Set timeout to 8 hours (480 minutes)

    steps:
    - name: Set up repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y git-lfs python3 curl
        if ! command -v python3 &> /dev/null; then 
          echo "Python3 not found, attempting reinstall"; 
          sudo apt install -y python3; 
        fi
        if ! command -v python &> /dev/null; then 
          sudo ln -s /usr/bin/python3 /usr/bin/python; 
        fi
        echo "Python version:" $(python3 --version)
        
    - name: Add Python to PATH
      run: echo "/usr/bin/python3" >> $GITHUB_PATH

    - name: Download and Install Latest Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Set up Git LFS
      run: git lfs install

    - name: Initialize RisingOS Repository
      env:
        PATH: ~/bin:$PATH:/usr/bin  # Ensuring /usr/bin is in the PATH for python3
      run: |
        repo init -u https://github.com/RisingTechOSS/android -b fifteen
        timeout 480m repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j4  # 8 hours timeout

    - name: Set up build environment
      run: . build/envsetup.sh

    - name: Start RisingOS build
      env:
        RISING_DEVICE: "sky"            
        RISING_BUILD_TYPE: "userdebug"   
      run: |
        riseup $RISING_DEVICE $RISING_BUILD_TYPE
        rise b

    - name: Archive build outputs
      run: |
        mkdir -p output
        cp out/target/product/sky/*.zip output/  

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}  
      with:
        tag_name: "build-${{ github.run_id }}"
        release_name: "RisingOS Build ${{ github.run_id }}"
        draft: false
        prerelease: true

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}  
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.zip
        asset_name: RisingOS-${{ github.run_id }}.zip
        asset_content_type: application/zip
