name: Build RisingOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y git-lfs python3 curl  # Ensure git-lfs, python3, and curl are installed
        # Create symlink for python3 if needed
        if ! command -v python &> /dev/null; then sudo ln -s /usr/bin/python3 /usr/bin/python; fi

    - name: Download and Install Latest Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH  # Add the new repo location to PATH

    - name: Set up Git LFS
      run: git lfs install

    - name: Initialize RisingOS Repository
      env:
        PATH: ~/bin:$PATH  # Ensure the new repo binary is used here as well
      run: |
        repo init -u https://github.com/RisingTechOSS/android -b fifteen
        repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j$(nproc --all)

    - name: Set up build environment
      run: . build/envsetup.sh

    - name: Start RisingOS build
      env:
        RISING_DEVICE: "sky"            # Device name
        RISING_BUILD_TYPE: "userdebug"   # Build type
      run: |
        riseup $RISING_DEVICE $RISING_BUILD_TYPE
        rise b

    - name: Archive build outputs
      run: |
        mkdir -p output
        cp out/target/product/sky/*.zip output/   # Update this path if necessary

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}  # Use your personal access token secret name here
      with:
        tag_name: "build-${{ github.run_id }}"
        release_name: "RisingOS Build ${{ github.run_id }}"
        draft: false
        prerelease: true

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}  # Use your personal access token secret name here
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.zip                    # Path to build output
        asset_name: RisingOS-${{ github.run_id }}.zip
        asset_content_type: application/zip
