name: Build RisingOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up repository
      uses: actions/checkout@v3

    - name: Set up Git LFS
      run: |
        sudo apt update
        sudo apt install -y git-lfs
        git lfs install

    - name: Initialize RisingOS Repository
      run: |
        repo init -u https://github.com/RisingTechOSS/android -b fifteen --git-lfs
        repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j$(nproc --all)

    - name: Remove problematic GMS files
      run: |
        rm -rf vendor/gms
        rm -rf .repo/projects/vendor/gms.git
        rm -rf .repo/project-objects/*/android_vendor_gms.git

    - name: Set up build environment
      run: . build/envsetup.sh

    - name: Start RisingOS build
      env:
        RISING_DEVICE: "sky"            # Device name
        RISING_BUILD_TYPE: "userdebug"   # Build type
      run: |
        riseup $RISING_DEVICE $RISING_BUILD_TYPE
        rise b

    - name: Archive build outputs
      run: |
        mkdir -p output
        cp out/target/product/sky/*.zip output/   # Update this path if necessary

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ghp_11AVEBS7I0eP0fwAZT1Uup_rdQQWPuIrYdjdtnKWegsMkmw6ZrDf7EqPP7wH8KNKMx3NJ2O2ANTYNd1VlV  # Replace with your token (Not Recommended)
      with:
        tag_name: "build-${{ github.run_id }}"
        release_name: "RisingOS Build ${{ github.run_id }}"
        draft: false
        prerelease: true

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ghp_11AVEBS7I0eP0fwAZT1Uup_rdQQWPuIrYdjdtnKWegsMkmw6ZrDf7EqPP7wH8KNKMx3NJ2O2ANTYNd1VlV  # Replace with your token (Not Recommended)
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.zip                    # Path to build output
        asset_name: RisingOS-${{ github.run_id }}.zip
        asset_content_type: application/zip
